export const NOTES_LIST_REQUEST = "NOTE_LISTS_REQUEST";
export const NOTES_LIST_SUCCESS = "NOTE_LISTS_SUCCESS";
export const NOTES_LIST_FAIL = "NOTE_LISTS_FAIL";


export const NOTES_CREATE_REQUEST = "NOTE_CREATE_REQUEST";
export const NOTES_CREATE_SUCCESS = "NOTE_CREATE_SUCCESS";
export const NOTES_CREATE_FAIL = "NOTE_CREATE_FAIL";

export const NOTES_DELETE_REQUEST = "NOTE_DELETE_REQUEST";
export const NOTES_DELETE_SUCCESS = "NOTE_DELETE_SUCCESS";
export const NOTES_DELETE_FAIL = "NOTE_DELETE_FAIL";